---
kind: pipeline
name: default

workspace:
  base: /go
  path: src/github.com/mohemohe/becomochi

steps:
  - name: docker build and push
    image: plugins/docker
    build_args_from_env:
      - DRONE_BRANCH
      - DRONE_COMMIT_SHA
    settings:
      repo: mohemohe/becomochi
      username:
        from_secret: dockerhub_username
      password:
        from_secret: dockerhub_password
    when:
      branch:
        - master
        - develop
